import time
from datetime import datetime
from typing import Any, Dict, List, Tuple
from fastapi import FastAPI, Request
from pydantic import BaseModel

import composer
import conversation_handlers

app = FastAPI()
START = time.time()

# In-memory stores
contexts: Dict[Tuple[str, str], dict] = {}
conversations: Dict[str, List] = {}

@app.get("/v1/healthz")
async def healthz():
    counts = {"category": 0, "merchant": 0, "customer": 0, "trigger": 0}
    for (scope, _), _ in contexts.items():
        counts[scope] = counts.get(scope, 0) + 1
    return {"status": "ok", "uptime_seconds": int(time.time() - START), "contexts_loaded": counts}

@app.get("/v1/metadata")
async def metadata():
    return {
        "team_name": "Antigravity",
        "team_members": ["Agent"],
        "model": "template-composer",
        "approach": "Template-based composer with deterministic output for reliability",
        "contact_email": "agent@example.com",
        "version": "1.0.0",
        "submitted_at": datetime.utcnow().isoformat() + "Z"
    }

class CtxBody(BaseModel):
    scope: str
    context_id: str
    version: int
    payload: Dict[str, Any]
    delivered_at: str

@app.post("/v1/context")
async def push_context(body: CtxBody):
    key = (body.scope, body.context_id)
    cur = contexts.get(key)
    if cur and cur["version"] >= body.version:
        return {"accepted": False, "reason": "stale_version", "current_version": cur["version"]}
    
    contexts[key] = {"version": body.version, "payload": body.payload}
    return {
        "accepted": True, 
        "ack_id": f"ack_{body.context_id}_v{body.version}",
        "stored_at": datetime.utcnow().isoformat() + "Z"
    }

class TickBody(BaseModel):
    now: str
    available_triggers: List[str] = []

@app.post("/v1/tick")
async def tick(body: TickBody):
    actions = []
    
    for trg_id in body.available_triggers:
        trg = contexts.get(("trigger", trg_id), {}).get("payload")
        if not trg: continue
        
        merchant_id = trg.get("merchant_id")
        merchant = contexts.get(("merchant", merchant_id), {}).get("payload")
        
        category = None
        if merchant:
            category_slug = merchant.get("category_slug")
            category = contexts.get(("category", category_slug), {}).get("payload")
            
        if not (merchant and category): continue
        
        customer_id = trg.get("customer_id")
        customer = contexts.get(("customer", customer_id), {}).get("payload") if customer_id else None
        
        try:
            # Compose message using our composer
            composed = composer.compose(category, merchant, trg, customer)
            
            actions.append({
                "conversation_id": f"conv_{merchant_id}_{trg_id}",
                "merchant_id": merchant_id, 
                "customer_id": customer_id,
                "send_as": composed.get("send_as", "vera"),
                "trigger_id": trg_id,
                "template_name": "vera_composed_v1",
                "template_params": [],
                "body": composed.get("body", "Hello"),
                "cta": composed.get("cta", "open_ended"),
                "suppression_key": composed.get("suppression_key", trg.get("suppression_key", "")),
                "rationale": composed.get("rationale", "Generated by composer")
            })
        except Exception as e:
            print(f"Error composing for {trg_id}: {e}")
            
    return {"actions": actions}

class ReplyBody(BaseModel):
    conversation_id: str
    merchant_id: str | None = None
    customer_id: str | None = None
    from_role: str
    message: str
    received_at: str
    turn_number: int

@app.post("/v1/reply")
async def reply(body: ReplyBody):
    history = conversations.setdefault(body.conversation_id, [])
    history.append({"from": body.from_role, "msg": body.message})
    
    try:
        response = conversation_handlers.respond(history, body.message)
        
        # Add bot's reply to history if it sent a message
        if response.get("action") == "send":
            history.append({"from": "vera", "msg": response.get("body", "")})
            
        return response
    except Exception as e:
        print(f"Error in reply handler: {e}")
        return {
            "action": "end",
            "rationale": "Error in processing reply"
        }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("bot:app", host="0.0.0.0", port=8080, reload=True)
